<?php

use Illuminate\Database\Seeder;
use App\AppsSettings;

class AppsSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        $settingsItApp = array(
        // Application Information General
            // Status
            array( 'field' => 'AppInfoGeneralStatus', 'value' => 'Active', ),
            array( 'field' => 'AppInfoGeneralStatus', 'value' => 'Inactive', ),
            array( 'field' => 'AppInfoGeneralStatus', 'value' => 'PENDING EDA PKG BUILD', ),
            array( 'field' => 'AppInfoGeneralStatus', 'value' => 'PENDING EOL', ),
            array( 'field' => 'AppInfoGeneralStatus', 'value' => 'PENDING GO-LIVE', ),
            array( 'field' => 'AppInfoGeneralStatus', 'value' => 'Pending Testing', ),
            array( 'field' => 'AppInfoGeneralStatus', 'value' => 'PENDING TRC APPROVAL', ),
            // First Contact Group
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'ACCESS', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'AMBULATORY COMMUNITY SYSTEMS SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'AMBULATORY EHR SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'BP HRIS', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'CARDIOVASCULAR & PERIOPERATIVE SYSTEMS SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'CLINICAL IMAGING SYSTEMS SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'CLINICAL INTERFACES', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'COMMUNITY CONNECT EHR', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'COMMUNITY CONNECT TECHNICAL', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'COMPUTER OPERATIONS', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'CORE SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'CTS', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'DATABASE ADMINISTRATION', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'DECISION SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'DEPARTMENT APPLICATIONS', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'DESIGN', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'DEVICE REFRESH', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'DISTRIBUTED SYSTEM SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'DOCUMENT IMAGING', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'EDA', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'ENTERPRISE RESOURCE MGMT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'ENTITY COORDINATORS', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'TECHNOLOGIES SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'HR Operations', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'IDENTITY & ACCESS MANAGEMENT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'INFRASTRUCTURE SERVICES', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'INPATIENT PHARMACY', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'IS Administration', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'ISD PURCHASING', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'ISD RECEIVING', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'IT INFRASTRUCTURE ADMIN', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'IT RISK MANAGEMENT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'IT TEAM', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'IT TECHNICAL SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'LABORATORY SYSTEMS SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'Leadership', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'MANAGED CARE', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'MASTER DATA MANAGEMENT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'NETWORK TECHNICAL SERVICES', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'NURSING SUPPROT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'OCIO', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'PATIENT CARE TECH ANALYST', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'PDS', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'PERIOPERATIVE SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'PHYSICIAN & PHARMACY SYSTEMS SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'PHYSICIAN SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'PORTFOLIO COLLABORATION MGT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'PRACTICE MANAGEMENT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'PROJECT MANAGEMENT OFFICE', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'PSS PROCUREMENT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'REVENUE MANAGEMENT SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'RM PROGRAMMER TEAM & ENROLLMENT SUPPORT', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'RMS DEVELOPMENT TEAM', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'RMS WEB SERVICES', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'SHC SECURITY', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'SITE SUPPORT LEADERSHIP', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'SITE SUPPORT SERVICES', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'TECHNICAL', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'TECHNICAL SERVICES', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'TELECOMMUNICATIONS', ),
            array( 'field' => 'AppInfoGeneralFirstContactGroup', 'value' => 'WEB', ),
            // Category
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Ambulatory Clinic EMR', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Application Management', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Cardiology', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Care Coordination', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Care Team', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Coding', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Community Care', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Compliance', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Data Governance', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Dietary', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Document Imaging', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Emergency Department', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Facilities Management', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Finance', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Gl Endo Lab', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'HIM', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Hospital Based Clinics', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Host Defense', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Human Resources', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Integration', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Internal Audit', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Labor and Delivery', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Laboratory', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Long Term Care', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Managed Care', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Network Security - External', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Network Security - Internal', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Other', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Patient', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Payroll', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Perimeter Defense', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Pharmacy Outpatient', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Physician', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Population Health', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Quality & Safety', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Radiology', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Radiology Oncology', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Rehabilitation', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Respiratory', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Retail Pharmacy', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Revenue Cycle Inpatient', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Revenu Cycle Outpatient', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Supply Chain', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Surgical', ),
            array( 'field' => 'AppInfoGeneralCategory', 'value' => 'Training', ),
            // Type
            array( 'field' => 'AppInfoGeneralType', 'value' => 'Database', ),
            array( 'field' => 'AppInfoGeneralType', 'value' => 'Desktop', ),
            array( 'field' => 'AppInfoGeneralType', 'value' => 'Device', ),
            array( 'field' => 'AppInfoGeneralType', 'value' => 'Dongle', ),
            array( 'field' => 'AppInfoGeneralType', 'value' => 'Operating System', ),
            array( 'field' => 'AppInfoGeneralType', 'value' => 'Server Only', ),
            array( 'field' => 'AppInfoGeneralType', 'value' => 'System Tools', ),
            array( 'field' => 'AppInfoGeneralType', 'value' => 'URL', ),
            // App Management
            array( 'field' => 'AppInfoGeneralAppManagement', 'value' => 'Hybrid Internal/Vendor Managed', ),
            array( 'field' => 'AppInfoGeneralAppManagement', 'value' => 'Internally Managed', ),
            array( 'field' => 'AppInfoGeneralAppManagement', 'value' => 'Vendor Managed', ),
            // Server Hosting Model
            array( 'field' => 'AppInfoGeneralServerHostingModel', 'value' => 'Self Hosted', ),
            array( 'field' => 'AppInfoGeneralServerHostingModel', 'value' => 'Multi-Tenant', ),
            array( 'field' => 'AppInfoGeneralServerHostingModel', 'value' => 'Vendor Hosted', ),
            array( 'field' => 'AppInfoGeneralServerHostingModel', 'value' => 'Vendor Website', ),
            array( 'field' => 'AppInfoGeneralServerHostingModel', 'value' => 'N/A', ),
        // Application Information Security
            // SSN
            array( 'field' => 'AppInfoSecuritySSN', 'value' => 'Full SSN Displayed', ),
            array( 'field' => 'AppInfoSecuritySSN', 'value' => 'Full Masked', ),
            array( 'field' => 'AppInfoSecuritySSN', 'value' => 'Last 4 Digits Displayed', ),
            array( 'field' => 'AppInfoSecuritySSN', 'value' => 'Not Used', ),
        // Contract
            // Term Unit
            array( 'field' => 'ContractTermUnit', 'value' => 'Days', ),
            array( 'field' => 'ContractTermUnit', 'value' => 'Months', ),
            array( 'field' => 'ContractTermUnit', 'value' => 'Years', ),
        // Licensing
            // Type
            array( 'field' => 'LicensingType', 'value' => 'Concurrent License', ),
            array( 'field' => 'LicensingType', 'value' => 'Enterprise License', ),
            array( 'field' => 'LicensingType', 'value' => 'N/A', ),
            array( 'field' => 'LicensingType', 'value' => 'Other', ),
            array( 'field' => 'LicensingType', 'value' => 'Single License', ),
            array( 'field' => 'LicensingType', 'value' => 'Subscription', ),
        // Dependency
            // Type
            array( 'field' => 'DependencyType', 'value' => '.NET', ),
            array( 'field' => 'DependencyType', 'value' => 'Active X', ),
            array( 'field' => 'DependencyType', 'value' => 'Android OS (Tablet)', ),
            array( 'field' => 'DependencyType', 'value' => 'cache.ini', ),
            array( 'field' => 'DependencyType', 'value' => 'Chrome', ),
            array( 'field' => 'DependencyType', 'value' => 'Dongle', ),
            array( 'field' => 'DependencyType', 'value' => 'File System', ),
            array( 'field' => 'DependencyType', 'value' => 'Flash', ),
            array( 'field' => 'DependencyType', 'value' => 'Internet Explorer', ),
            array( 'field' => 'DependencyType', 'value' => 'Internet Explorer 11', ),
            array( 'field' => 'DependencyType', 'value' => 'Java', ),
            array( 'field' => 'DependencyType', 'value' => 'LDAP', ),
            array( 'field' => 'DependencyType', 'value' => 'Lumninex software by Vendor', ),
            array( 'field' => 'DependencyType', 'value' => 'MS Exchange', ),
            array( 'field' => 'DependencyType', 'value' => 'MS Office', ),
            array( 'field' => 'DependencyType', 'value' => 'MS Office - ACCESS', ),
            array( 'field' => 'DependencyType', 'value' => 'MS SQL Server', ),
            array( 'field' => 'DependencyType', 'value' => 'MS Windows Server', ),
            array( 'field' => 'DependencyType', 'value' => 'mTilda', ),
            array( 'field' => 'DependencyType', 'value' => 'Silverlight', ),
            array( 'field' => 'DependencyType', 'value' => 'Windows OS', ),
            // App Build
            array( 'field' => 'DependencyAppBuild', 'value' => '64 Bit', ),
            array( 'field' => 'DependencyAppBuild', 'value' => 'N/A', ),
            // EDA Package Build
            array( 'field' => 'DependencyEDAPackageBuild', 'value' => 'N/A', ),
            array( 'field' => 'DependencyEDAPackageBuild', 'value' => 'No', ),
            array( 'field' => 'DependencyEDAPackageBuild', 'value' => 'Waiting CRQ', ),
            array( 'field' => 'DependencyEDAPackageBuild', 'value' => 'Yes', ),
            // Updated Exec Path
            array( 'field' => 'DependencyUpdatedExecPath', 'value' => 'N/A', ),
            array( 'field' => 'DependencyUpdatedExecPath', 'value' => 'No', ),
            array( 'field' => 'DependencyUpdatedExecPath', 'value' => 'Yes', ),
            // Updated install Notes
            array( 'field' => 'DependencyUpdatedinstallNotes', 'value' => 'Analyst Follow-up', ),
            array( 'field' => 'DependencyUpdatedinstallNotes', 'value' => 'N/A', ),
            array( 'field' => 'DependencyUpdatedinstallNotes', 'value' => 'No', ),
            array( 'field' => 'DependencyUpdatedinstallNotes', 'value' => 'Yes', ),
            // DCT Status
            array( 'field' => 'DependencyDCTStatus', 'value' => 'Failed', ),
            array( 'field' => 'DependencyDCTStatus', 'value' => 'N/A', ),
            array( 'field' => 'DependencyDCTStatus', 'value' => 'Passed', ),
            array( 'field' => 'DependencyDCTStatus', 'value' => 'Pending', ),
            array( 'field' => 'DependencyDCTStatus', 'value' => 'Retest', ),
            // App Compliant
            array( 'field' => 'DependencyAppCompliant', 'value' => 'Conflicts', ),
            array( 'field' => 'DependencyAppCompliant', 'value' => 'N/A', ),
            array( 'field' => 'DependencyAppCompliant', 'value' => 'No', ),
            array( 'field' => 'DependencyAppCompliant', 'value' => 'Unknown', ),
            array( 'field' => 'DependencyAppCompliant', 'value' => 'Yes', ),
        // Specifications Certification
            // Type
            array( 'field' => 'SpecificationsCertificationType', 'value' => 'FedRamp', ),
            array( 'field' => 'SpecificationsCertificationType', 'value' => 'ISO 27001', ),
            array( 'field' => 'SpecificationsCertificationType', 'value' => 'Other', ),
            array( 'field' => 'SpecificationsCertificationType', 'value' => 'PCI', ),
        // Specifications Maintenance
            // Operating System
            array( 'field' => 'SpecificationsMaintenanceOperatingSystem', 'value' => 'Android', ),
            array( 'field' => 'SpecificationsMaintenanceOperatingSystem', 'value' => 'iOS', ),
            array( 'field' => 'SpecificationsMaintenanceOperatingSystem', 'value' => 'Linux', ),
            array( 'field' => 'SpecificationsMaintenanceOperatingSystem', 'value' => 'Mac OSX', ),
            array( 'field' => 'SpecificationsMaintenanceOperatingSystem', 'value' => 'Microsoft Windows', ),
            array( 'field' => 'SpecificationsMaintenanceOperatingSystem', 'value' => 'Other', ),
            // Future Operating System
            array( 'field' => 'SpecificationsMaintenanceFutureOperatingSystem', 'value' => 'Android', ),
            array( 'field' => 'SpecificationsMaintenanceFutureOperatingSystem', 'value' => 'iOS', ),
            array( 'field' => 'SpecificationsMaintenanceFutureOperatingSystem', 'value' => 'Linux', ),
            array( 'field' => 'SpecificationsMaintenanceFutureOperatingSystem', 'value' => 'Microsoft Windows', ),
            array( 'field' => 'SpecificationsMaintenanceFutureOperatingSystem', 'value' => 'Unix', ),
            // IP Address Type
            array( 'field' => 'SpecificationsMaintenanceIPAddressType', 'value' => 'LAN', ),
            array( 'field' => 'SpecificationsMaintenanceIPAddressType', 'value' => 'WAN', ),
            // Network Zone Type
            array( 'field' => 'SpecificationsMaintenanceNetworkZoneType', 'value' => 'Campus', ),
            array( 'field' => 'SpecificationsMaintenanceNetworkZoneType', 'value' => 'Department', ),
            array( 'field' => 'SpecificationsMaintenanceNetworkZoneType', 'value' => 'Enterprise', ),
        // Install General
            // Type
            array( 'field' => 'InstallGeneralType', 'value' => 'APM', ),
            array( 'field' => 'InstallGeneralType', 'value' => 'LAN Desk Software Dist', ),
            array( 'field' => 'InstallGeneralType', 'value' => 'Manual', ),
            array( 'field' => 'InstallGeneralType', 'value' => 'Vendor', ),
            // Delivery Method
            array( 'field' => 'InstallGeneralDeliveryMethod', 'value' => 'APM/Manual', ),
            array( 'field' => 'InstallGeneralDeliveryMethod', 'value' => 'Citrix', ),
            array( 'field' => 'InstallGeneralDeliveryMethod', 'value' => 'Desktop Install', ),
            array( 'field' => 'InstallGeneralDeliveryMethod', 'value' => 'NA', ),
            array( 'field' => 'InstallGeneralDeliveryMethod', 'value' => 'Web', ),
            array( 'field' => 'InstallGeneralDeliveryMethod', 'value' => 'Web or Citrix', ),
            // Windows Passed DCT
            array( 'field' => 'InstallGeneralWindowsPassedDCT', 'value' => 'Yes', ),
            array( 'field' => 'InstallGeneralWindowsPassedDCT', 'value' => 'No', ),
            array( 'field' => 'InstallGeneralWindowsPassedDCT', 'value' => 'Windows not needed', ),
            // LDAP/AD Authentication
            array( 'field' => 'InstallGeneralLDAP/ADAuthentication', 'value' => 'LDAP/AD 2012 R2', ),
            array( 'field' => 'InstallGeneralLDAP/ADAuthentication', 'value' => 'LDAP/AD 2016', ),
            array( 'field' => 'InstallGeneralLDAP/ADAuthentication', 'value' => 'LDAP/AD 2019 R2', ),
            array( 'field' => 'InstallGeneralLDAP/ADAuthentication', 'value' => 'N/A', ),
        // Rationalization Costs
            // Category
            array( 'field' => 'RationalizationCostsCategory', 'value' => 'Initial Capital', ),
            array( 'field' => 'RationalizationCostsCategory', 'value' => 'Initial Operating', ),
            array( 'field' => 'RationalizationCostsCategory', 'value' => 'One-time capital', ),
            array( 'field' => 'RationalizationCostsCategory', 'value' => 'One-time operating', ),
            array( 'field' => 'RationalizationCostsCategory', 'value' => 'Ongoing', ),
            array( 'field' => 'RationalizationCostsCategory', 'value' => 'Other', ),
            // Type
            array( 'field' => 'RationalizationCostsType', 'value' => 'Consulting', ),
            array( 'field' => 'RationalizationCostsType', 'value' => 'Contract Staffing', ),
            array( 'field' => 'RationalizationCostsType', 'value' => 'Implementation', ),
            array( 'field' => 'RationalizationCostsType', 'value' => 'Maintenance & Support', ),
            array( 'field' => 'RationalizationCostsType', 'value' => 'Other', ),
            array( 'field' => 'RationalizationCostsType', 'value' => 'Service', ),
            array( 'field' => 'RationalizationCostsType', 'value' => 'Subscription', ),
            array( 'field' => 'RationalizationCostsType', 'value' => 'Training IT', ),
            array( 'field' => 'RationalizationCostsType', 'value' => 'Training User', ),
            array( 'field' => 'RationalizationCostsType', 'value' => 'Vendor Staffing', ),
            // Owner
            array( 'field' => 'RationalizationCostsOwner', 'value' => 'Customer', ),
            array( 'field' => 'RationalizationCostsOwner', 'value' => 'IT', ),
            array( 'field' => 'RationalizationCostsOwner', 'value' => 'Other', ),
            // Period
            array( 'field' => 'RationalizationCostsPeriod', 'value' => 'Annual', ),
            array( 'field' => 'RationalizationCostsPeriod', 'value' => 'Annual pd Monthly', ),
            array( 'field' => 'RationalizationCostsPeriod', 'value' => 'Annual pd Quarterly', ),
            array( 'field' => 'RationalizationCostsPeriod', 'value' => 'One time', ),
        // Rationalization Licensing
            // Purchase Type
            array( 'field' => 'RationalizationLicensingPurchaseType', 'value' => 'Lease', ),
            array( 'field' => 'RationalizationLicensingPurchaseType', 'value' => 'Other', ),
            array( 'field' => 'RationalizationLicensingPurchaseType', 'value' => 'Owner', ),
            array( 'field' => 'RationalizationLicensingPurchaseType', 'value' => 'SaaS', ),
            array( 'field' => 'RationalizationLicensingPurchaseType', 'value' => 'Subscription', ),
            // License Type
            array( 'field' => 'RationalizationLicensingLicenseType', 'value' => 'Concurrent License' ),
            array( 'field' => 'RationalizationLicensingLicenseType', 'value' => 'Enterprise License' ),
            array( 'field' => 'RationalizationLicensingLicenseType', 'value' => 'N/A' ),
            array( 'field' => 'RationalizationLicensingLicenseType', 'value' => 'Other' ),
            array( 'field' => 'RationalizationLicensingLicenseType', 'value' => 'Single License' ),
            array( 'field' => 'RationalizationLicensingLicenseType', 'value' => 'Subscription' ),
        // Rationalization FTE
            // Type
            array( 'field' => 'RationalizationFTEType', 'value' => 'Customer', ),
            array( 'field' => 'RationalizationFTEType', 'value' => 'IT Application Analyst', ),
            array( 'field' => 'RationalizationFTEType', 'value' => 'IT Field Support', ),
            array( 'field' => 'RationalizationFTEType', 'value' => 'IT Technical', ),
            array( 'field' => 'RationalizationFTEType', 'value' => 'Other', ),
            array( 'field' => 'RationalizationFTEType', 'value' => 'Vendor', ),
        // Rationalization User
            // Type
            array( 'field' => 'RationalizationUserType', 'value' => 'Estimated Concurrent Users', ),
            array( 'field' => 'RationalizationUserType', 'value' => 'Estimated Users', ),
        // Rationalization Governance
            // Responsible Division
            array( 'field' => 'RationalizationGovernanceRespDivision', 'value' => 'Ambulatory Community', ),
            array( 'field' => 'RationalizationGovernanceRespDivision', 'value' => 'Ancillary Services', ),
            array( 'field' => 'RationalizationGovernanceRespDivision', 'value' => 'Enterprise Solutions', ),
            array( 'field' => 'RationalizationGovernanceRespDivision', 'value' => 'Inpatient Systems', ),
            array( 'field' => 'RationalizationGovernanceRespDivision', 'value' => 'Revenue Management & ERM', ),
            // Responsible Committee
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Cardiology', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Clinical Imaging', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'CNO Council', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Data Governance', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Document Imaging', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Emergency Department (ED) IS', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Enterprise Analytics', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Enterprise Resource Management (ERM)', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Health Information Exchange (HIE)', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Home Health/Hospice', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'HR/Workforce', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Information Security Advisory Committee', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Inpatient (IP) Pharmacy', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'IS Ambulatory Electronic Health Record (AEHR)', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'IT Exec', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Lab', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Managed Care', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Patient Care Executive', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Patient/Consumer', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Perioperative/Surgery', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Project Magement - Facilities Modernization', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Project Portfolio Collaboration Management', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Radiation Oncology', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Retail Pharmacy', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Revenue Management Clinics', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Revenue Management Hospital', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'SCMG IS Steering', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Supply Chain', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Technical Services', ),
            array( 'field' => 'RationalizationGovernanceRespCommittee', 'value' => 'Web Steering', ),
            // First Contact Group
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'ACCESS', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'AMBULATORY EHR SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'BP HRIS', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'CARDIOVASCULAR & PERIOPERATIVE SYSTEMS SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'BP HRIS', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'CARDIOVASCULAR & PERIOPERATIVE SYSTEMS SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'CLINICAL IMAGING SYSTEMS SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'CLINICAL INTERFACES', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'COMUNITY CONNECT TECHNICAL', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'COMPUTER Other', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'CORE SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'CTS', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'DATABASE ADMINISTRATION', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'DECISION SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'DEPARTMENT APPLICATIONS', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'DESIGN', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'DEVICE DEPLOYMENT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'DEVICE REFRESH', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'DISTRIBUTED SYSTEMS SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'DOCUMENT IMAGING', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'EDA', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'ENTERPRISE RESOURCE MGMT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'ENTITY APPLICATIONS', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'ENTITY COORDINATORS', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'FACILITY TECHNOLOGIES SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'HR Operations', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'IDENTITY & ACCESS MANAGEMENT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'INFRASTRUCTURE SERVICES', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'INPATIENT PHARMACY', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'INTEROPERABILITY', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'IS Administration', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'ISD PURCHASING', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'ISD RECEIVING', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'IT INFRASTRUCTURE ADMIN', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'IT RISK MANAGEMENT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'IT TEAM', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'IT TECHNICAL SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'LABORATORY SYSTEMS SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'Leadership', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'MANAGED CARE', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'MASTER DATA MANAGEMENT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'NETWORK TECHNICAL SERVICES', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'NURSING SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'OCIO', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'PATIENT CARE TECH ANALYST', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'PDS', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'PERIOPERATIVE SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'PHYSICIAN & PHARMACY SYSTEMS SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'PHYSICIAN SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'PORTFOLIO COLLABORATION MGT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'PRACTICE MANAGEMENT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'PROJECT MANAGEMENT OFFICE', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'PSS PROCUREMENT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'REVENUE MANAGEMENT SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'RM PROGRAMMER TEAM & ENROLLMENT SUPPORT', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'RMS DEVELOPMENT TEAM', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'RMS WEB SERVICES', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'SHC SERVICES', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'SITE SUPPORT LEADERSHIP', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'SITE SUPPORT SERVICES', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'TECHNICAL', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'TECHNICAL SERVICES', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'TELECOMMUNICATIONS', ),
            array( 'field' => 'RationalizationGovernanceFirstContactGroup', 'value' => 'WEB', ),
        // Rationalization Attributes
            // Kind
            array( 'field' => 'RationalizationAttributesKind', 'value' => 'Eliminated', ),
            array( 'field' => 'RationalizationAttributesKind', 'value' => 'Invest', ),
            array( 'field' => 'RationalizationAttributesKind', 'value' => 'Migrate', ),
            array( 'field' => 'RationalizationAttributesKind', 'value' => 'Tolerate', ),
            // Application Value
            array( 'field' => 'RationalizationAttributesAppValue', 'value' => 'Financial/Revenue', ),
            array( 'field' => 'RationalizationAttributesAppValue', 'value' => 'Only Vendor', ),
            array( 'field' => 'RationalizationAttributesAppValue', 'value' => 'Additional Comments', ),
            array( 'field' => 'RationalizationAttributesAppValue', 'value' => 'Quality', ),
            array( 'field' => 'RationalizationAttributesAppValue', 'value' => 'Regulatory/Compliance', ),
            array( 'field' => 'RationalizationAttributesAppValue', 'value' => 'Safely/Reliability', ),
            array( 'field' => 'RationalizationAttributesAppValue', 'value' => 'Service/Productivity', )
        );

        $settingsWorkOrder= array(
            // Status
            array( 'field' => 'wo_status',       'value' => 'In Progress', ),
            array( 'field' => 'wo_status',       'value' => 'Pending',     ),
            array( 'field' => 'wo_status',       'value' => 'Complete',    ),
            array( 'field' => 'wo_status',       'value' => 'Declined',    ),
            // Request Type
            array( 'field' => 'wo_request_type', 'value' => 'Approval',    ),
            array( 'field' => 'wo_request_type', 'value' => 'General',     )
        );

        foreach($settingsItApp as $setting){
            AppsSettings::create([
                'field' => $setting['field'],
                'value' => $setting['value'],
                'app_type'=> 'itapp'
            ]);
        }

        foreach($settingsWorkOrder as $setting){
            AppsSettings::create([
                'field' => $setting['field'],
                'value' => $setting['value'],
                'app_type'=> 'm6works'
            ]);
        }
    }
}
